DROP TABLE CAT IF EXISTS CASCADE;
DROP TABLE PROD IF EXISTS CASCADE;
DROP TABLE SEQUENCES IF EXISTS CASCADE;

CREATE TABLE CAT (
    ID INTEGER NOT NULL,
   	NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE PROD (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255),
    PRICE NUMERIC(16,2),
    CAT_ID INTEGER,
    PRIMARY KEY (ID)
);

ALTER TABLE PROD 
    ADD CONSTRAINT FK_PROD_CAT_ID
    FOREIGN KEY (CAT_ID) 
    REFERENCES CAT;

CREATE TABLE SEQUENCES (
     NAME VARCHAR(255),
     VALUE INTEGER 
);